apiVersion: v1
kind: Namespace
metadata:
  name: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
    spec:
      containers:
      - name: facebook
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: facebook-svc
  namespace: app
spec:
  selector:
    app: facebook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facebook-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - secretName: selfsigned
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: facebook-svc
            port:
              number: 8080
